DROP TABLE IF EXISTS actual_visit;
DROP TABLE IF EXISTS planned_visit;
DROP TABLE IF EXISTS planned_route;
DROP TABLE IF EXISTS ship;
DROP TABLE IF EXISTS ship_type;
DROP TABLE IF EXISTS berth;
DROP TABLE IF EXISTS port;
DROP TABLE IF EXISTS country;
